stages:
  - build

# 프론트엔드 빌드
frontend-build:
  stage: build
  image: node:18-alpine  # 사용할 Docker 이미지
  script:
    - echo "Building frontend"
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      - frontend/dist  # 빌드 결과물을 artifacts로 저장
  only:
    - front  # 'front' 브랜치에만 빌드 실행
  tags:
    - frontend  # 'frontend' 태그가 있는 GitLab Runner에서만 실행
  services:
    - docker:dind  # Docker-in-Docker를 사용하여 Docker 서비스 활성화
  variables:
    DOCKER_DRIVER: overlay2  # Docker Driver 설정