stages:
  - build

# 프론트엔드 빌드
frontend-build:
  stage: build
  image: node:18-alpine
  script:
    - echo "Building frontend"
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      - frontend/dist
  only:
    - front # 프론트 브랜에만 빌드 실행
  tags:
    - frontend  # frontend 태그가 있는 러너에서만 실행

# 백엔드 빌드
backend-build:
  stage: build
  image: gradle:jdk17
  script:
    - echo "Building backend"
    - cd backend
    - ./gradlew build
  artifacts:
    paths:
      - backend/build/libs/*.jar
  tags:
    - backend  # backend 태그가 있는 러너에서만 실행

# 프론트엔드 배포
frontend-deploy:
  stage: deploy
  script:
    - echo "Deploying frontend"
    - cd frontend
    - # 실제 배포 스크립트 작성 (예: Docker, AWS S3 등)
  tags:
    - frontend  # frontend 태그가 있는 러너에서만 실행

# 백엔드 배포
backend-deploy:
  stage: deploy
  script:
    - echo "Deploying backend"
    - cd backend
    - # 실제 배포 스크립트 작성 (예: Docker, AWS EC2 등)
  tags:
    - backend  # backend 태그가 있는 러너에서만 실행
