stages:
  - build

# 프론트엔드 빌드
frontend-build:
  stage: build
  image: node:18-alpine
  script:
    - echo "Building frontend"
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      - frontend/dist
  only:
    - front # 프론트 브랜에만 빌드 실행
  tags:
    - frontend  # frontend 태그가 있는 러너에서만 실행