spring:
  profiles:
    active: prod
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

logging:
  level:
    root: info
    sql: debug
    org.hibernate.SQL: debug
#    org.hibernate.type: trace
    org.springframework.security: debug
    com.ssafy.wevi: debug
